### ISSUE TITLE
non-existent roads

### ISSUE THREAD

**Issue by antblant** [ppawel/osmonitor#37]
S12 & S16 are only on paper
I suggest to remove them from the report

**Comment by ppawel** [comment]
I think instead of removing I will put some information in the input data that the road should not have any components or something - it will stay in the report and be green.

**Comment by jzvc** [comment]
In czech, there is D47, which is cancelled project - D47 is included to D1 for now. See https://cs.wikipedia.org/wiki/D%C3%A1lnice_D47

**Comment by ppawel** [comment]
I marked S12, S17, D47 and couple more roads in Poland as having 0 components.

See files:

https://github.com/ppawel/osmonitor/blob/master/data/road_refs/CR.csv
https://github.com/ppawel/osmonitor/blob/master/data/road_refs/PL.csv

If you want you can mark more roads as such by adding 0 in the num_comps CSV column. You can also insert proper number of components there instead of tagging relation with osmonitor:road_components tag.
